### Create new type
@baseUrl = http://localhost:5000

POST {{baseUrl}}/api/types
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NiwiZW1haWwiOiJhZG1pbkBtYWlsLnJ1Iiwicm9sZSI6IkFETUlOIiwiaWF0IjoxNjU2NjA5NzMxLCJleHAiOjE2NTY2OTYxMzF9.TSE474YHELIOMV99VkIrPWmlroquFSfU9H5vYMWjCi8
Content-Type: application/json

{
	"name": "Холодильники"
}

### Get all types
GET {{baseUrl}}/api/types


### Get type with brands
GET {{baseUrl}}/api/types/32

### Get type with brands
GET {{baseUrl}}/api/types/32?brands=true

### Get type with devices
GET {{baseUrl}}/api/types/32?devices=true

### Get type with devices & brands
GET {{baseUrl}}/api/types/32?devices=true&brands=true