@baseUrl = http://localhost:5000

### Создание новго пользователся
POST {{baseUrl}}/api/users/registration
Content-Type: application/json

{
	"email": "admin@mail.ru",
	"password": "admin"
}

### Логин пользователся
# @name auth
POST {{baseUrl}}/api/users/login HTTP/1.1
Content-Type: application/json;charset=UTF-8

{
	"email": "admin@mail.ru",
	"password": "admin"
}

###

GET {{baseUrl}}/api/users/auth
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6NSwiZW1haWwiOiJ1c2VyMUBtYWlsLnJ1Iiwicm9sZSI6IlVTRVIiLCJpYXQiOjE2NTY2MDc3MDQsImV4cCI6MTY1NjY5NDEwNH0.3g6flGyD783sZ6zRKrRuPIHk0uo9JlBzpXIOQBWbgxs